name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face (LevelBot)
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: lunarflu/levelbot
        huggingface_repo_id: lunarflu/LevelBot
        repo_type: space
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN_WRITE }}
